USE aquapoint;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE reports;
TRUNCATE TABLE reviews;
TRUNCATE TABLE favorites;
TRUNCATE TABLE points_state;
TRUNCATE TABLE trust_logs;
TRUNCATE TABLE aqua_points;
TRUNCATE TABLE users;
TRUNCATE TABLE trustLevels;
TRUNCATE TABLE states;
TRUNCATE TABLE local;
TRUNCATE TABLE zone;
TRUNCATE TABLE type;

SET FOREIGN_KEY_CHECKS = 1;